GET http://localhost:5000/users

###
POST http://localhost:5000/signup
Content-Type: application/json

{   
    "name":"kousik",
    "username":"kousik22",
    "password": "Kousik@123",
    "gender": "Male"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"kousik22",
    "password": "Kousik@123"
}

###

GET http://localhost:5000/blog

###


GET http://localhost:5000/portfolio

###

POST http://localhost:5000/updateportfolio
Content-Type: application/json

{
"id":"5",
"title":"wikipedia search",
"url":"https://kousikwikipedia.ccbp.tech/",
"imageUrl":"https://i.ibb.co/QJjHyQB/wikipedia-search.jpg",
"github":"https://codepen.io/Ramachandruni-Kousik/pen/mdGjmPo"
}